chore: fixes.

diff --git a/.github/workflows/eas.release.native.yml b/.github/workflows/eas.release.native.yml
--- a/.github/workflows/eas.release.native.yml
+++ b/.github/workflows/eas.release.native.yml
@@ -20,13 +20,8 @@ jobs:
       - uses: actions/setup-node@v3
         with:
           node-version: 18.x
-          cache: npm
-
-      - name: Configure Yarn for Public Repos
-        run: echo "always-auth false" >> ~/.yarnrc
-
-      - name: Configure NPM for Public Repos
-        run: echo "always-auth=false" >> ~/.npmrc
+          cache: yarn
+          cache-dependency-path: '**/yarn.lock'
 
       - name: Setup Expo and EAS
         uses: expo/expo-github-action@v8
@@ -36,11 +31,7 @@ jobs:
 
       - name: Install dependencies
         working-directory: packages/clippy
-        run: npm install --no-audit --prefer-offline
-
-      - name: Prepare (link) iOS UserDefaults (suite) package
-        working-directory: packages/user-defaults-suite-ios
-        run: npm run prepare
+        run: yarn install
 
       - name: Create dummy appclip Info.plist for npx expo-config
         working-directory: packages/clippy
@@ -49,18 +40,22 @@ jobs:
           mkdir -p ios/ClippyClip
           touch ios/ClippyClip/Info.plist
 
+      - name: Debug Environment
+        working-directory: app/packages/payy
+        run: |
+          echo "Node version: $(node -v)"
+          echo "npm version: $(npm -v)"
+          echo "Expo CLI version: $(npx expo --version)"
+          EXPO_DEBUG=true npx expo config --json --type introspect || echo "Command failed with exit code $?"
+
+      - name: Prepare (link) iOS UserDefaults (suite) package
+        working-directory: packages/user-defaults-suite-ios
+        run: yarn prepare
+
       - name: Build and Submit on EAS (iOS and Android)
         if: ${{ github.event.inputs.skip_ios != 'true' && github.event.inputs.skip_android != 'true' }}
         working-directory: packages/clippy
-        run: |
-          echo "Current directory: $(pwd)"
-          if [[ -f $(pwd)/ios/ClippyClip/Info.plist ]]; then
-            echo "Dummy Info.plist exists"
-          else
-            echo "Dummy Info.plist does not exist"
-          fi
-        
-          EXPO_NO_CAPABILITY_SYNC=1  eas build --platform all --non-interactive #--auto-submit
+        run: EXPO_NO_CAPABILITY_SYNC=1  eas build --platform all --non-interactive --auto-submit
 
       - name: Build and Submit on EAS (iOS)
         if: ${{ github.event.inputs.skip_ios != 'true' && github.event.inputs.skip_android == 'true' }}
